### ISSUE TITLE
notes do not keep newlines

### ISSUE THREAD

**Issue by kparal** [wbasile/Open-Game-Benchmarks#18]
When filling benchmark notes, it's a large multi-line text field. However, the newlines are then ignored when displayed:
http://www.opengamebenchmarks.org/benchmark_detail/326

Should look like this:

> extreme anti-aliasing
> TargetSmooth30FPS and FPSCapEnabled disabled in ~/.frozenbyte/Trine2/options.txt

**Comment by wbasile** [comment]
fixed!

**Comment by kparal** [comment]
This is still an issue when hovering the mouse cursor over "view notes" field in a benchmark overview mode, e.g. here:
http://www.opengamebenchmarks.org/benchmark_table/?game=Trine%202
